robot_hardware:
    - la_sr_ur_robot_hw
la_sr_ur_robot_hw:
  type: ur_driver/HardwareInterface
  
  # ra for right side arm la for left side arm
  robot_id: la
  
  # for sending robot programs
  robot_ip_address: 192.168.0.2
  
  # for the server that moves the robot 
  control_pc_ip_address: 192.168.0.100
